### ISSUE TITLE
Error in ReID training using MOT17 dataset

### ISSUE THREAD

**Issue by Leael** [dvl-tum/GHOST#14]
I used the MOT17 dataset that can be downloaded in https://motchallenge.net/data/MOT17/
I created a `datasets` folder inside the ReID folder
then used `tools/train.py` but got this error:

Traceback (most recent call last):
  File "train.py", line 35, in <module>
    main(args)
  File "train.py", line 30, in main
    trainer.train()
  File "/home/jupyter/GHOST/ReID/utils/trainer.py", line 139, in train
    self.get_data()
  File "/home/jupyter/GHOST/ReID/utils/trainer.py", line 398, in get_data
    num_elements_class=self.train_config.num_elements_class)
  File "/home/jupyter/GHOST/ReID/data/data_utility.py", line 37, in create_loaders
    num_elements_class)
  File "/home/jupyter/GHOST/ReID/data/data_utility.py", line 60, in get_train_dataloader
    sz_crop=dataset_config.sz_crop)
  File "/home/jupyter/GHOST/ReID/data/MOTdata.py", line 74, in __init__
    df_all = self.get_sequencess(ann_files, min_vis, min_h, min_w, min_samples)
  File "/home/jupyter/GHOST/ReID/data/MOTdata.py", line 96, in get_sequencess
    with open(ann_file) as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/MOT17/annotations/MOT17_MOT17-02.json'

how to fix this? or may I know the dataset format needed

**Comment by JennySeidenschwarz** [comment]
Hey :) I added the data to our webshare and updated the README. If you download the data it should work smoothly!
