### ISSUE TITLE
AttributeError: 'DataFrame' object has no attribute 'append'

### ISSUE THREAD

**Issue by Tobelakers** [dvl-tum/GHOST#18]
When I ran "bash scripts/main_17.sh", the following error occurred:
Traceback (most recent call last):
  File "tools/main_track.py", line 93, in <module>
    main_track(args)
  File "tools/main_track.py", line 79, in main_track
    manager = Manager(
  File "/home/sunzhaojie/GHOST/./src/manager.py", line 96, in __init__
    self.loaders = self._get_loaders(dataset_cfg)
  File "/home/sunzhaojie/GHOST/./src/manager.py", line 159, in _get_loaders
    dataset = TrackingDataset(
  File "/home/sunzhaojie/GHOST/./src/datasets/TrackingDataset.py", line 66, in __init__
    self.process()
  File "/home/sunzhaojie/GHOST/./src/datasets/TrackingDataset.py", line 94, in process
    exist_gt = loader.get_seqs(self.assign_gt)
  File "/home/sunzhaojie/GHOST/./src/datasets/MOT17_parser.py", line 63, in get_seqs
    self.assign_gt_clear(split)
  File "/home/sunzhaojie/GHOST/./src/datasets/MOT17_parser.py", line 313, in assign_gt_clear
    self.corresponding_gt = self.corresponding_gt.append(
  File "/home/sunzhaojie/.conda/envs/mot24/lib/python3.8/site-packages/pandas/core/generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'append'
I still haven't solved it after debugging, and I hope to get your reply.
Thank you for your excellent work!

**Comment by Tobelakers** [comment]
solved
